[project]
name = "vlm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "clip",
    "numpy>=2.5.2",
    "pillow>=12.3.0",
    "pytorch-lightning>=2.6.5",
    "rasterio>=1.5.1",
    "streamlit>=1.62.0",
    "streamlit-image-select>=0.6.0",
    "terratorch==1.2.2",
    "torchgeo==0.9.0",
]

[tool.uv.sources]
clip = { git = "https://github.com/openai/CLIP.git" }
